# Why you need it ?

# Internet
#     ↓
# Traefik (Ingress) — route le trafic vers les services K8s
#     ↓
# Service K8s (ClusterIP)
#     ↓
# Pod (container)
#     ├── Nginx (ou serve)  ← sert les fichiers statiques HTML/JS/CSS

# After running `npm run build`, you’ll have a `dist/` folder full of static files.
# You need something to serve them. Your options:


# Without a server inside the pod, your built files will never be served.
# Nginx or serve — they do the same thing, but Nginx is 50 times lighter.
# Traefik doesn’t do that — Traefik’s routing is Layer 7 (HTTP);
# it can’t serve files from the pod’s disk.


user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 20M;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript
               application/x-javascript application/xml+rss
               application/javascript application/json;

    server {
    server_tokens off;
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        # Sert les assets (JS, CSS, images) directement
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            # Permet du caching long terme pour les assets
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # Route SPA: envoie toutes les requêtes inconnues vers index.html
        # Cela permet à Vue Router de gérer le routing côté client
        location / {
            try_files $uri $uri/ /index.html;
            open_file_cache max=1000 inactive=20s;
        }
    }
}